/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pop3.server;

public class App {
    public static void main(String[] args) {
        var pop3Server = new Pop3Server();
        pop3Server.open();
    }
}
