/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pop3.client;

public class App {

    public static void main(String[] args) {
        try (var pop3Client = new Pop3Client()) {
            pop3Client.open("outlook.office365.com", 995);
            pop3Client.readResponse();
            pop3Client.user("dan.egg@outlook.com");
            pop3Client.readResponse();
            pop3Client.pass("");
            pop3Client.readResponse();
            pop3Client.stat();
            pop3Client.readResponse();
            pop3Client.quit();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

}
